name: Download Model

on:
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  download_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download u2net.onnx model
      run: |
        curl -L https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net.onnx -o u2net.onnx

    - name: Commit and push the model file
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add u2net.onnx
        git commit -m "Add u2net.onnx model"
        git push
